// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGT8fvkwQ07NvCQCZPMIoC5UCkp-qrhU',
    appId: '1:1048618485774:web:80e4bcde2c1b79838c145f',
    messagingSenderId: '1048618485774',
    projectId: 'rahbar-app-b0b13',
    authDomain: 'rahbar-app-b0b13.firebaseapp.com',
    storageBucket: 'rahbar-app-b0b13.appspot.com',
    measurementId: 'G-CG94Z3S2E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKKwXOUeTAsYRO3dthTOK8jyBkL4NTMw',
    appId: '1:1048618485774:android:cf13b0c870fd0b268c145f',
    messagingSenderId: '1048618485774',
    projectId: 'rahbar-app-b0b13',
    storageBucket: 'rahbar-app-b0b13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnS6GHRQyK9eFeiaV3-FFicbyPnnP1_SY',
    appId: '1:1048618485774:ios:851638354b1186c58c145f',
    messagingSenderId: '1048618485774',
    projectId: 'rahbar-app-b0b13',
    storageBucket: 'rahbar-app-b0b13.appspot.com',
    iosBundleId: 'com.example.projectAppdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnS6GHRQyK9eFeiaV3-FFicbyPnnP1_SY',
    appId: '1:1048618485774:ios:ecf789190dc04c208c145f',
    messagingSenderId: '1048618485774',
    projectId: 'rahbar-app-b0b13',
    storageBucket: 'rahbar-app-b0b13.appspot.com',
    iosBundleId: 'com.example.projectAppdev.RunnerTests',
  );
}
